
--Create table query
CREATE TABLE retail_sales(
 	transactions_id INT PRIMARY KEY,
	sale_date DATE,
	sale_time TIME,
	customer_id INT,
	gender VARCHAR(10),
	age INT,
	category VARCHAR(20),
	quantiy INT,
	price_per_unit NUMERIC(10,2),
	cogs NUMERIC(10,2),
	total_sale NUMERIC(10,2)
);

--Find the NULL value
SELECT * FROM RETAIL_SALES
WHERE
	TRANSACTIONS_ID IS NULL
	OR SALE_DATE IS NULL
	OR SALE_TIME IS NULL
	OR CUSTOMER_ID IS NULL
	OR GENDER IS NULL
	OR AGE IS NULL
	OR CATEGORY IS NULL
	OR QUANTIY IS NULL
	OR PRICE_PER_UNIT IS NULL
	OR COGS IS NULL
	OR TOTAL_SALE IS NULL;

--Delete the Null value
DELETE FROM RETAIL_SALES
WHERE
	TRANSACTIONS_ID IS NULL
	OR SALE_DATE IS NULL
	OR SALE_TIME IS NULL
	OR CUSTOMER_ID IS NULL
	OR GENDER IS NULL
	OR AGE IS NULL
	OR CATEGORY IS NULL
	OR QUANTIY IS NULL
	OR PRICE_PER_UNIT IS NULL
	OR COGS IS NULL
	OR TOTAL_SALE IS NULL;

--How many sales we have
SELECT COUNT(*) FROM retail_sales;

--How many customer we have
SELECT COUNT(DISTINCT customer_id) FROM retail_sales;

--Show category we have
SELECT DISTINCT category FROM retail_sales;


--AVG AGE of Customer
SELECT AVG(age) AS AVG_age FROM retail_sales;

--find the avg quantity 
SELECT AVG(quantiy) AS AVG_quantity FROM retail_sales;

--find avg total sale
SELECT AVG(total_sale) AS AVG_total_sale FROM retail_sales;

--count the male and female customer
SELECT gender,COUNT(*) FROM retail_sales GROUP BY  gender;

--find the highest price_per_unit
SELECT * FROM retail_sales ORDER BY price_per_unit DESC LIMIT 1;

--Retreive the column for sales made on '2022-11-05'
SELECT * FROM retail_sales WHERE sale_date = '2022-11-05';

--Retreive all transactions where the category is 'Clothing' and quantity sold more
--than or equal to 4 AND sales made on '2022-11'
SELECT * FROM retail_sales 
WHERE category='Clothing' AND quantiy >= 4 AND TO_CHAR(sale_date,'YYYY-MM')='2022-11';

--calculate the total sales for each category
SELECT category,SUM(total_sale),COUNT(*) AS total_order
FROM retail_sales 
GROUP BY category;

--find the avg age of customer who purchase item from beauty category
SELECT category,ROUND(AVG(age),2) AS AVG_AGE
FROM retail_sales 
GROUP BY category HAVING category='Beauty';

--Find all transaction where the total_Sale is > 1000
SELECT *
FROM retail_sales 
WHERE total_sale > 1000;

--Display the transaction between two dates (ex: 2022-11-06 to 2022-11-22) 
SELECT * FROM retail_sales WHERE sale_date BETWEEN '2022-11-06' AND '2022-11-22';

----------------------------------------------------------------------------------------
--find total number of transaction (transactions_id) made by each gender in each category
SELECT category,gender,COUNT(transactions_id) AS TOTAL_transaction
FROM retail_sales 
GROUP BY category,gender ORDER BY 1;

--Calculate avg sale for each month , find out best selling month in each year
SELECT year,month,avg_sale FROM(
SELECT EXTRACT(YEAR FROM sale_date) AS year,
	   EXTRACT(MONTH FROM sale_date) AS month,
	   AVG(total_sale) AS avg_sale,
	   RANK() OVER(PARTITION BY EXTRACT(YEAR FROM sale_date) 
	   ORDER BY AVG(total_sale) DESC)AS RANK
FROM retail_sales 
GROUP BY EXTRACT(YEAR FROM sale_date) ,EXTRACT(MONTH FROM sale_date) ORDER BY 1,3 DESC)
WHERE RANK=1;

--find the top 5 customer based on the highest total sale
SELECT customer_id,SUM(total_sale) AS total_Sale 
FROM retail_sales
GROUP BY 1 ORDER BY SUM(total_sale) DESC LIMIT 5;

--Find the number of unique customer who purchased item from each category
SELECT category,COUNT(DISTINCT customer_id) AS count_UNIQUE_CUSTOMER
FROM retail_sales
GROUP BY 1;

--write a sql query to create each shift and number of orders
--(ex: morning<=12,between 12 to 17 ,evening >17)
SELECT SHIFT,COUNT(*) AS number_of_order FROM (
SELECT *,
	CASE
		WHEN EXTRACT(HOUR FROM sale_time)< 12 THEN 'Morning'
		WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
		ELSE 'Evening'
	END AS SHIFT
FROM retail_sales)
GROUP BY SHIFT;

SELECT * FROM retail_sales;

--Display all tranaction where total ale is greater than average
SELECT * FROM retail_sales WHERE total_sale > ( SELECT AVG(total_sale) AS AVG_total_sale
FROM retail_sales);

--find the total revenue generated by each gender
SELECT gender,SUM(total_sale) as total_revenue FROM retail_sales group by gender;

--Calculate monthly sale revenue 
SELECT EXTRACT(YEAR FROM sale_date) AS year,
	   EXTRACT(MONTH FROM sale_date) AS month,
	   SUM(total_sale) AS total_sale
FROM retail_sales
GROUP BY 1,2 ORDER BY 1,2; 

--find the number of transaction by each day
SELECT sale_date,COUNT(*) AS total_transaction FROM  retail_sales
GROUP BY  sale_date ORDER BY sale_date;

--find the category whose total revenue exceeds 50000
SELECT category,SUM(total_sale) AS total_revenue 
FROM  retail_sales
GROUP BY  category HAVING SUM(total_sale)  > 50000;

-----------------------------------------------------------------------------------------

SELECT * FROM retail_sales;

--find the top 5 customer based on total spending
SELECT customer_id,SUM(total_sale) AS total_spending 
FROM  retail_sales
GROUP BY  customer_id ORDER BY total_spending DESC LIMIT 5;

--Rank customer by total sale using RANK()
SELECT customer_id,SUM(total_sale) AS total_spending,
RANK() OVER(ORDER BY SUM(total_sale) DESC) AS RANK
FROM  retail_sales
GROUP BY  customer_id ORDER BY total_spending DESC;

--find the second highest sale amount
SELECT total_sale FROM (
SELECT total_sale,
DENSE_RANK() OVER(ORDER BY total_sale DESC) AS RANK
FROM  retail_sales
)AS RANKED WHERE RANK=2;

SELECT DISTINCT total_sale FROM  retail_sales 
ORDER BY total_sale DESC OFFSET 1 LIMIT 1;

--Find customer s who made more than 5 purchased
SELECT customer_id,COUNT(*) AS total_purchased 
FROM  retail_sales 
GROUP BY customer_id HAVING COUNT(*) > 5 ORDER BY total_purchased DESC ;

--Find the category with the highest avg sale
SELECT category,AVG(total_sale) AS avg_sale 
FROM  retail_sales 
GROUP BY category ORDER BY avg_sale DESC LIMIT 1;

--Find the top selling category by quantity
SELECT category,SUM(quantiy) AS total_quantity 
FROM  retail_sales 
GROUP BY category ORDER BY  total_quantity DESC LIMIT 1;

--calculate each category's percentage contribution to the total revenue
SELECT category,SUM(total_sale) AS total_revenue,
ROUND((SUM(total_sale)*100)/(SELECT SUM(total_sale)FROM  retail_sales ),2) AS contribution
FROM  retail_sales 
GROUP BY category;

--SELECT the First and Last date for each customer
SELECT customer_id,MIN(sale_date) AS First_date,MAX (sale_date) AS Last_date
FROM  retail_sales
GROUP BY  customer_id;

--Find sale made during morning , afternoon, evening
SELECT SHIFT,SUM(total_sale) as total_Sale FROM (
SELECT *,
	CASE
		WHEN EXTRACT(HOUR FROM sale_time)< 12 THEN 'Morning'
		WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
		ELSE 'Evening'
	END AS SHIFT
FROM retail_sales)
GROUP BY SHIFT;

--calculate month over month sale growth
SELECT EXTRACT(YEAR FROM sale_date) AS year,
		EXTRACT(MONTH FROM sale_date) AS month,
		SUM(total_sale) as total_Sale ,
		LAG(SUM(total_sale),1,0) 
		OVER(ORDER BY  EXTRACT(YEAR FROM sale_date), EXTRACT(MONTH FROM sale_date)) 
		AS previous_month_sale,
		ROUND((SUM(total_sale)-
		LAG(SUM(total_sale),1,0) 
		OVER(ORDER BY  EXTRACT(YEAR FROM sale_date), EXTRACT(MONTH FROM sale_date)))*100/
		LAG(SUM(total_sale)) 
		OVER(ORDER BY EXTRACT(YEAR FROM sale_date),EXTRACT(MONTH FROM sale_date)),2)AS GROWTH
FROM retail_sales
GROUP BY 1,2 ORDER BY 1,2;		


--find the customer whose spending above the avg customer spending
SELECT customer_id,SUM(total_sale) AS total_spending
FROM  retail_sales
GROUP BY  customer_id 
HAVING SUM(total_sale) > (
SELECT AVG(customer_total) FROM (
SELECT SUM(total_sale) AS customer_total FROM retail_sales GROUP BY customer_id
) );


